Create deploy manifests

diff --git a/.github/workflows/build-deploy-aks.yaml b/.github/workflows/build-deploy-aks.yaml
--- a/.github/workflows/build-deploy-aks.yaml
+++ b/.github/workflows/build-deploy-aks.yaml
@@ -74,6 +74,29 @@ jobs:
         with:
           creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID  }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
           enable-AzPSSession: true
+          
+      - name: Deploy manifests
+        run: |
+          IMAGE = ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
+
+          if [ -z "$IMAGE" ]; then
+            echo "ERROR: Image value is empty."
+            exit 1
+          fi
+
+          kubectl apply -f labs/practitioner/01-github-actions-to-aks/k8s/namespace.yaml
+
+          kubectl apply -f labs/practitioner/01-github-actions-to-aks/k8s\service.yaml
+          
+          sed "s|IMAGE_PLACEHOLDER|${IMAGE}|g" \
+            labs/practitioner/01-github-actions-to-aks/k8s/deployment.yaml \
+            | kubectl apply -f -
+
+          
+
+
+
+
 
 
 
